### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by phi1010** [kressi/terminalplot#3]
terminalplot depends on termios and fcntl, which are not available on an Anaconda Python interpreter running on Windows -- probably neither on the official one. Even when specifying columns and rows manually; including these modules alone already prevents terminalplot from being used on Windows.

**Comment by kressi** [comment]
1. [Python: What OS am I running on?](https://stackoverflow.com/a/1857)
2. [Determine size of console window on Windows](http://code.activestate.com/recipes/440694-determine-size-of-console-window-on-windows/)

```python
from ctypes import windll, create_string_buffer

# stdin handle is -10
# stdout handle is -11
# stderr handle is -12

h = windll.kernel32.GetStdHandle(-12)
csbi = create_string_buffer(22)
res = windll.kernel32.GetConsoleScreenBufferInfo(h, csbi)

if res:
    import struct
    (bufx, bufy, curx, cury, wattr,
     left, top, right, bottom, maxx, maxy) = struct.unpack("hhhhHhhhhhh", csbi.raw)
    sizex = right - left + 1
    sizey = bottom - top + 1
else:
    sizex, sizey = 80, 25 # can't determine actual size - return default values

print sizex, sizey
```

**Comment by kressi** [comment]
Supports now also Windows. Added a build on Travis for Windows as well. https://travis-ci.org/kressi/terminalplot/jobs/624243458 Build passes, tests do not get found by nose. I could not figure out why. At least it should no longer crash on Windows.
